# db connection
db.url=jdbc:postgresql://localhost:5432/bank
db.driver=org.postgresql.Driver
db.username=postgres
db.password=1234

# to support uppercase columns (1) and tables (2)
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT
jwt.secret=some_jwt_key_11111111111111111111111111111111111111111111111111111
jwt.expiration=3600000

# flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration