CREATE TABLE "USER" (
    "ID" BIGINT PRIMARY KEY,
    "NAME" VARCHAR(500) NOT NULL,
    "DATE_OF_BIRTH" DATE NOT NULL,
    "PASSWORD" VARCHAR(500) NOT NULL CHECK ( LENGTH("PASSWORD") >= 8 )
);

CREATE TABLE "ACCOUNT" (
   "ID" BIGINT PRIMARY KEY,
   "USER_ID" BIGINT UNIQUE NOT NULL REFERENCES "USER"("ID") ON DELETE CASCADE,
   "BALANCE" DECIMAL CHECK ( "BALANCE" >= 0 )
);

CREATE TABLE "EMAIL_DATA" (
  "ID" BIGINT PRIMARY KEY,
  "USER_ID" BIGINT NOT NULL REFERENCES "USER"("ID") ON DELETE CASCADE,
  "EMAIL" VARCHAR(200) UNIQUE
);

CREATE TABLE "PHONE_DATA" (
  "ID" BIGINT PRIMARY KEY,
  "USER_ID" BIGINT NOT NULL REFERENCES "USER"("ID") ON DELETE CASCADE,
  "PHONE" VARCHAR(13) UNIQUE NOT NULL CHECK ( LENGTH("PHONE") >= 6 )
);

-- deposit increment

CREATE TABLE "ACCOUNT_DEPOSIT_INCREMENT" (
    "ACCOUNT_ID" BIGINT PRIMARY KEY REFERENCES "ACCOUNT"("ID") ON DELETE CASCADE,
    "INITIAL_BALANCE" DECIMAL NOT NULL,
    "CURRENT_BALANCE" DECIMAL NOT NULL,
    "LAST_INCREMENT_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION trg_account_after_insert()
    RETURNS trigger AS $$
BEGIN
    INSERT INTO "ACCOUNT_DEPOSIT_INCREMENT" ("ACCOUNT_ID", "INITIAL_BALANCE", "CURRENT_BALANCE", "LAST_INCREMENT_AT")
    VALUES (new."ID", new."BALANCE", new."BALANCE", CURRENT_TIMESTAMP);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER account_after_insert_trigger
    AFTER INSERT ON "ACCOUNT"
    FOR EACH ROW
EXECUTE FUNCTION trg_account_after_insert();