CREATE TABLE "USER" (
    "ID" BIGINT PRIMARY KEY,
    "NAME" VARCHAR(500) NOT NULL,
    "DATE_OF_BIRTH" DATE NOT NULL,
    "PASSWORD" VARCHAR(500) NOT NULL CHECK ( LENGTH("PASSWORD") >= 8 )
);

CREATE TABLE "ACCOUNT" (
   "ID" BIGINT PRIMARY KEY,
   "USER_ID" BIGINT UNIQUE NOT NULL REFERENCES "USER"("ID") ON DELETE CASCADE,
   "BALANCE" DECIMAL CHECK ( "BALANCE" >= 0 )
);

CREATE TABLE "EMAIL_DATA" (
  "ID" BIGINT PRIMARY KEY,
  "USER_ID" BIGINT NOT NULL REFERENCES "USER"("ID") ON DELETE CASCADE,
  "EMAIL" VARCHAR(200) UNIQUE
);

CREATE TABLE "PHONE_DATA" (
  "ID" BIGINT PRIMARY KEY,
  "USER_ID" BIGINT NOT NULL REFERENCES "USER"("ID") ON DELETE CASCADE,
  "PHONE" VARCHAR(13) UNIQUE NOT NULL CHECK ( LENGTH("PHONE") >= 6 )
);